name: EWallet CI (Backend)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: Publish artifact
        type: boolean
        required: true
        default: true
        
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore solution
        run: dotnet restore EWallet.slnx

      - name: Build solution
        run: dotnet build EWallet.slnx --configuration Release --no-restore

      - name: Run tests (ALL projects)
        run: dotnet test EWallet.slnx --configuration Release --no-build
